name: Documentation

on: [pull_request, push]

permissions:
  contents: write

jobs:
  Valadoc:
    name: Deploy Valadoc
    runs-on: ubuntu-latest
    container: 
      image: elementary/docker:unstable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: apt-get update && apt-get -y install libvala-dev valac git libgsl-dev python-pip && apt-get -y remove meson && pip install --user meson

      - name: Build
        run: meson build && ninja -C build
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc
